//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2Hours_Ver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string sessionID { get; set; }
        public int orderNumber { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> deliveryTime { get; set; }
        public Nullable<bool> deliveryStatus { get; set; }
        public Nullable<System.DateTime> updatedSession { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
