//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organic_Launch
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public int accountDetailID { get; set; }
        public Nullable<int> accountID { get; set; }
        public Nullable<int> farmID { get; set; }
        public Nullable<int> addressID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Farm Farm { get; set; }
        public virtual Address Address { get; set; }
    }
}
